# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TestMobileCenter' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for TestMobileCenter
  pod 'RNMobileCenter', '~> 0.4.0'
  pod 'MobileCenter', '~> 0.6.0'

  

  target 'TestMobileCenterTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'TestMobileCenter-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for TestMobileCenter-tvOS

  target 'TestMobileCenter-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
