# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TestMobileCenter' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for TestMobileCenter
  pod 'RNMobileCenter', '~> 0.4.0'
  pod 'MobileCenter', '~> 0.6.0'
  pod 'CodePush', :path => '../node_modules/react-native-code-push'

  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'RCTText',
    'RCTNetwork',
    'RCTWebSocket', # needed for debugging
    # Add any other subspecs you want to use in your project
  ]

  # Explicitly include Yoga if you are using RN >= 0.42.0
  pod "Yoga", :path => "../node_modules/react-native/ReactCommon/yoga"

  

  target 'TestMobileCenterTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'TestMobileCenter-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for TestMobileCenter-tvOS

  target 'TestMobileCenter-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
